### ISSUE TITLE
testに失敗する

### ISSUE THREAD

**Issue by pyonnuka** [pyonnuka/jpmobile#1]
1) Jpmobile::Mail delivering delivers through SMTP
     Failure/Error: expect {
       expected no Exception, got #<Errno::ECONNREFUSED: Connection refused - connect(2)> with backtrace:
         # ./vender/bundle/ruby/2.0.0/gems/mail-2.6.3/lib/mail/network/delivery_methods/smtp.rb:112:in `deliver!'
         # ./vender/bundle/ruby/2.0.0/gems/mail-2.6.3/lib/mail/message.rb:2141:in`do_delivery'
         # ./vender/bundle/ruby/2.0.0/gems/mail-2.6.3/lib/mail/message.rb:238:in `deliver'
         # ./spec/unit/mail_spec.rb:347:in`block (4 levels) in <top (required)>'
         # ./spec/unit/mail_spec.rb:346:in `block (3 levels) in <top (required)>'
     # ./spec/unit/mail_spec.rb:346:in`block (3 levels) in <top (required)>'

Finished in 0.75642 seconds (files took 0.35785 seconds to load)
319 examples, 1 failure

Failed examples:

rspec ./spec/unit/mail_spec.rb:344 # Jpmobile::Mail delivering delivers through SMTP

**Comment by pyonnuka** [comment]
テストを実行するときにメール転送エージェントが起動していないと落ちる。

```
1) Jpmobile::Mail delivering delivers through SMTP
Failure/Error: expect {
expected no Exception, got # with backtrace:
# ./vender/bundle/ruby/2.0.0/gems/mail-2.6.3/lib/mail/network/delivery_methods/smtp.rb:112:in deliver!' # ./vender/bundle/ruby/2.0.0/gems/mail-2.6.3/lib/mail/message.rb:2141:indo_delivery'
# ./vender/bundle/ruby/2.0.0/gems/mail-2.6.3/lib/mail/message.rb:238:in deliver' # ./spec/unit/mail_spec.rb:347:inblock (4 levels) in '
# ./spec/unit/mail_spec.rb:346:in block (3 levels) in <top (required)>' # ./spec/unit/mail_spec.rb:346:inblock (3 levels) in '

Finished in 0.75642 seconds (files took 0.35785 seconds to load)
319 examples, 1 failure

Failed examples:

rspec ./spec/unit/mail_spec.rb:344 # Jpmobile::Mail delivering delivers through SMTP
```
